services:
  db:
    image: postgres:16-alpine
    container_name: odonto_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # HEALTHCHECK: Garantía de Disponibilidad (SLA)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: odonto_backend
    restart: always
    # Conectamos las variables de entorno
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Espera a que la BD esté lista real
    # SEGURIDAD: Límite de recursos (Mitigación DoS - Ley 21.663)
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M




# --- NUEVO SERVICIO: FRONTEND ---
  frontend:
    build: ./frontend
    container_name: odonto_frontend
    restart: always
    ports:
      - "3000:3000"  # Mapeamos puerto 3000 del PC al 3000 del contenedor
    volumes:
      - ./frontend:/app           # Sincronización en vivo (Hot-reload)
      - /app/node_modules         # Evita conflictos de dependencias
    depends_on:
      - backend                   # Espera a que el backend exista


volumes:
  postgres_data:
